// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "ShootableInterface.generated.h"

// This class was generated by UE4 and should not be touched!
UINTERFACE(MinimalAPI)
class UShootableInterface : public UInterface
{
	GENERATED_BODY()
};

/**
 * Interface for any objects our player can shoot
 */
class VGDC_VR_API IShootableInterface
{
	GENERATED_BODY()

	// Add interface functions to this class. This is the class that will be inherited to implement this interface.
public:
	/**
	 * Called by the player when this object is shot
	 * 
	 * @return Just a placeholder so this works right in blueprints
	 */
	UFUNCTION(BlueprintCallable, BlueprintImplementableEvent, Category = "Shootable")
		bool OnShot();
	//virtual void Shoot_Implementation() override;
	
};
